ABS_X: true
ABS_Y: true
ABS_Z: true
ABS_RX: true
ABS_RY: true
ABS_RZ: true
ABS_THROTTLE: true
ABS_RUDDER: true
ABS_WHEEL: true
ABS_GAS: true
ABS_BRAKE: true
ABS_HAT0X: true
ABS_HAT0Y: true
ABS_HAT1X: true
ABS_HAT1Y: true
ABS_HAT2X: true
ABS_HAT2Y: true
ABS_HAT3X: true
ABS_HAT3Y: true
ABS_PRESSURE: true
ABS_DISTANCE: true
ABS_TILT_X: true
ABS_TILT_Y: true
ABS_TOOL_WIDTH: true
ABS_VOLUME: true
ABS_MISC: true
ABS_MT_SLOT: true
ABS_MT_TOUCH_MAJOR: true
ABS_MT_TOUCH_MINOR: true
ABS_MT_WIDTH_MAJOR: true
ABS_MT_WIDTH_MINOR: true
ABS_MT_ORIENTATION: true
ABS_MT_POSITION_X: true
ABS_MT_POSITION_Y: true
ABS_MT_TOOL_TYPE: true
ABS_MT_BLOB_ID: true
ABS_MT_TRACKING_ID: true
ABS_MT_PRESSURE: true
ABS_MT_DISTANCE: true
ABS_MT_TOOL_X: true
ABS_MT_TOOL_Y: true
