#!/usr/bin/bash
cur=$(xprop -root -notype _NET_CURRENT_DESKTOP | cut -d= -f2)

case "$cur" in
	" 0")
		ws="● ○ ○ ○"
		;;
	" 1")
		ws="○ ● ○ ○"
		;;
	" 2")
		ws="○ ○ ● ○"
		;;
	" 3")
		ws="○ ○ ○ ●"
		;;
esac
echo "$ws"

